// flow-typed signature: 1b4e99dfdb1ae0f3102b041f2864d0ce
// flow-typed version: <<STUB>>/esprima-fb_v^15001.1001.0-dev-harmony-fb/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esprima-fb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esprima-fb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esprima-fb/bin/esparse' {
  declare module.exports: any;
}

declare module 'esprima-fb/bin/esvalidate' {
  declare module.exports: any;
}

declare module 'esprima-fb/esprima' {
  declare module.exports: any;
}

declare module 'esprima-fb/test/compat' {
  declare module.exports: any;
}

declare module 'esprima-fb/test/reflect' {
  declare module.exports: any;
}

declare module 'esprima-fb/test/run' {
  declare module.exports: any;
}

declare module 'esprima-fb/test/runner' {
  declare module.exports: any;
}

declare module 'esprima-fb/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esprima-fb/bin/esparse.js' {
  declare module.exports: $Exports<'esprima-fb/bin/esparse'>;
}
declare module 'esprima-fb/bin/esvalidate.js' {
  declare module.exports: $Exports<'esprima-fb/bin/esvalidate'>;
}
declare module 'esprima-fb/esprima.js' {
  declare module.exports: $Exports<'esprima-fb/esprima'>;
}
declare module 'esprima-fb/test/compat.js' {
  declare module.exports: $Exports<'esprima-fb/test/compat'>;
}
declare module 'esprima-fb/test/reflect.js' {
  declare module.exports: $Exports<'esprima-fb/test/reflect'>;
}
declare module 'esprima-fb/test/run.js' {
  declare module.exports: $Exports<'esprima-fb/test/run'>;
}
declare module 'esprima-fb/test/runner.js' {
  declare module.exports: $Exports<'esprima-fb/test/runner'>;
}
declare module 'esprima-fb/test/test.js' {
  declare module.exports: $Exports<'esprima-fb/test/test'>;
}
