// flow-typed signature: 3a1181893724af476ec2b9b4197ae1d3
// flow-typed version: <<STUB>>/jscs_v^3.0.7/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jscs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jscs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jscs/lib/checker' {
  declare module.exports: any;
}

declare module 'jscs/lib/cli-config' {
  declare module.exports: any;
}

declare module 'jscs/lib/cli' {
  declare module.exports: any;
}

declare module 'jscs/lib/config/configuration' {
  declare module.exports: any;
}

declare module 'jscs/lib/config/generator' {
  declare module.exports: any;
}

declare module 'jscs/lib/config/node-configuration' {
  declare module.exports: any;
}

declare module 'jscs/lib/errors' {
  declare module.exports: any;
}

declare module 'jscs/lib/extract-js' {
  declare module.exports: any;
}

declare module 'jscs/lib/get-cli' {
  declare module.exports: any;
}

declare module 'jscs/lib/js-file' {
  declare module.exports: any;
}

declare module 'jscs/lib/reporters/checkstyle' {
  declare module.exports: any;
}

declare module 'jscs/lib/reporters/console' {
  declare module.exports: any;
}

declare module 'jscs/lib/reporters/inline' {
  declare module.exports: any;
}

declare module 'jscs/lib/reporters/inlinesingle' {
  declare module.exports: any;
}

declare module 'jscs/lib/reporters/json' {
  declare module.exports: any;
}

declare module 'jscs/lib/reporters/junit' {
  declare module.exports: any;
}

declare module 'jscs/lib/reporters/summary' {
  declare module.exports: any;
}

declare module 'jscs/lib/reporters/text' {
  declare module.exports: any;
}

declare module 'jscs/lib/reporters/unix' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-anonymous-functions' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-array-destructuring-return' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-arrow-functions' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-capitalized-comments' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-comma-before-line-break' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-curly-braces' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-dangling-underscores' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-empty-blocks' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-function-declarations' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-identical-destructuring-names' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-identifier-names' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-implicit-type-conversion' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-keywords-in-comments' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-keywords-on-new-line' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-keywords' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-mixed-spaces-and-tabs' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-multi-line-ternary' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-multiple-line-breaks' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-multiple-line-strings' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-multiple-spaces' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-multiple-var-decl' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-named-unassigned-functions' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-nested-ternaries' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-newline-before-block-statements' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-node-types' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-not-operators-in-conditionals' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-object-keys-on-new-line' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-operator-before-line-break' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-padding-newlines-after-blocks' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-padding-newlines-after-use-strict' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-padding-newlines-before-export' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-padding-newlines-before-keywords' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-padding-newlines-before-line-comments' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-padding-newlines-in-blocks' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-padding-newlines-in-objects' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-parentheses-around-arrow-param' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-quoted-keys-in-objects' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-semicolons' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-shorthand-arrow-functions' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-space-after-binary-operators' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-space-after-comma' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-space-after-keywords' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-space-after-line-comment' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-space-after-object-keys' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-space-after-prefix-unary-operators' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-space-before-binary-operators' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-space-before-block-statements' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-space-before-comma' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-space-before-keywords' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-space-before-object-values' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-space-before-postfix-unary-operators' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-space-before-semicolon' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-space-between-arguments' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-spaces-in-anonymous-function-expression' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-spaces-in-call-expression' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-spaces-in-conditional-expression' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-spaces-in-for-statement' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-spaces-in-function-declaration' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-spaces-in-function-expression' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-spaces-in-function' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-spaces-in-generator' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-spaces-in-named-function-expression' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-spaces-inside-array-brackets' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-spaces-inside-brackets' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-spaces-inside-imported-object-braces' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-spaces-inside-object-brackets' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-spaces-inside-parentheses' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-spaces-inside-parenthesized-expression' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-spaces-inside-template-string-placeholders' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-tabs' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-trailing-comma' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-trailing-whitespace' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-unused-params' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-unused-variables' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-var' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/disallow-yoda-conditions' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/jsdoc' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/maximum-line-length' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/maximum-number-of-lines' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-aligned-multiline-params' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-aligned-object-values' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-anonymous-functions' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-array-destructuring' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-arrow-functions' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-blocks-on-newline' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-camelcase-or-uppercase-identifiers' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-capitalized-comments' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-capitalized-constructors-new' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-capitalized-constructors' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-comma-before-line-break' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-curly-braces' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-dollar-before-jquery-assignment' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-dot-notation' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-early-return' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-enhanced-object-literals' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-function-declarations' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-imports-alphabetized' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-keywords-on-new-line' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-line-break-after-variable-assignment' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-line-feed-at-file-end' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-matching-function-name' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-multi-line-ternary' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-multiple-var-decl' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-named-unassigned-functions' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-newline-before-block-statements' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-newline-before-single-statements-in-if' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-numeric-literals' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-object-destructuring' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-object-keys-on-new-line' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-operator-before-line-break' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-padding-newline-after-variable-declaration' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-padding-newlines-after-blocks' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-padding-newlines-after-use-strict' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-padding-newlines-before-export' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-padding-newlines-before-keywords' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-padding-newlines-before-line-comments' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-padding-newlines-in-blocks' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-padding-newlines-in-objects' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-parentheses-around-arrow-param' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-parentheses-around-iife' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-quoted-keys-in-objects' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-semicolons' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-shorthand-arrow-functions' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-space-after-binary-operators' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-space-after-comma' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-space-after-keywords' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-space-after-line-comment' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-space-after-object-keys' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-space-after-prefix-unary-operators' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-space-before-binary-operators' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-space-before-block-statements' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-space-before-comma' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-space-before-destructured-values' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-space-before-keywords' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-space-before-object-values' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-space-before-postfix-unary-operators' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-space-between-arguments' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-spaces-in-anonymous-function-expression' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-spaces-in-call-expression' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-spaces-in-conditional-expression' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-spaces-in-for-statement' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-spaces-in-function-declaration' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-spaces-in-function-expression' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-spaces-in-function' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-spaces-in-generator' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-spaces-in-named-function-expression' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-spaces-inside-array-brackets' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-spaces-inside-brackets' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-spaces-inside-imported-object-braces' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-spaces-inside-object-brackets' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-spaces-inside-parentheses' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-spaces-inside-parenthesized-expression' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-spread' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-template-strings' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-trailing-comma' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-use-strict' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-var-decl-first' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/require-yoda-conditions' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/safe-context-keyword' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/validate-aligned-function-parameters' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/validate-comment-position' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/validate-indentation' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/validate-line-breaks' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/validate-newline-after-array-elements' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/validate-order-in-object-keys' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/validate-parameter-separator' {
  declare module.exports: any;
}

declare module 'jscs/lib/rules/validate-quote-marks' {
  declare module.exports: any;
}

declare module 'jscs/lib/string-checker' {
  declare module.exports: any;
}

declare module 'jscs/lib/token-assert' {
  declare module.exports: any;
}

declare module 'jscs/lib/token-categorizer' {
  declare module.exports: any;
}

declare module 'jscs/lib/token-index' {
  declare module.exports: any;
}

declare module 'jscs/lib/tree-iterator' {
  declare module.exports: any;
}

declare module 'jscs/lib/utils' {
  declare module.exports: any;
}

declare module 'jscs/patterns/identifiers-ES5' {
  declare module.exports: any;
}

declare module 'jscs/patterns/identifiers-ES6' {
  declare module.exports: any;
}

declare module 'jscs/patterns/L' {
  declare module.exports: any;
}

declare module 'jscs/patterns/Ll' {
  declare module.exports: any;
}

declare module 'jscs/patterns/Lu' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jscs/lib/checker.js' {
  declare module.exports: $Exports<'jscs/lib/checker'>;
}
declare module 'jscs/lib/cli-config.js' {
  declare module.exports: $Exports<'jscs/lib/cli-config'>;
}
declare module 'jscs/lib/cli.js' {
  declare module.exports: $Exports<'jscs/lib/cli'>;
}
declare module 'jscs/lib/config/configuration.js' {
  declare module.exports: $Exports<'jscs/lib/config/configuration'>;
}
declare module 'jscs/lib/config/generator.js' {
  declare module.exports: $Exports<'jscs/lib/config/generator'>;
}
declare module 'jscs/lib/config/node-configuration.js' {
  declare module.exports: $Exports<'jscs/lib/config/node-configuration'>;
}
declare module 'jscs/lib/errors.js' {
  declare module.exports: $Exports<'jscs/lib/errors'>;
}
declare module 'jscs/lib/extract-js.js' {
  declare module.exports: $Exports<'jscs/lib/extract-js'>;
}
declare module 'jscs/lib/get-cli.js' {
  declare module.exports: $Exports<'jscs/lib/get-cli'>;
}
declare module 'jscs/lib/js-file.js' {
  declare module.exports: $Exports<'jscs/lib/js-file'>;
}
declare module 'jscs/lib/reporters/checkstyle.js' {
  declare module.exports: $Exports<'jscs/lib/reporters/checkstyle'>;
}
declare module 'jscs/lib/reporters/console.js' {
  declare module.exports: $Exports<'jscs/lib/reporters/console'>;
}
declare module 'jscs/lib/reporters/inline.js' {
  declare module.exports: $Exports<'jscs/lib/reporters/inline'>;
}
declare module 'jscs/lib/reporters/inlinesingle.js' {
  declare module.exports: $Exports<'jscs/lib/reporters/inlinesingle'>;
}
declare module 'jscs/lib/reporters/json.js' {
  declare module.exports: $Exports<'jscs/lib/reporters/json'>;
}
declare module 'jscs/lib/reporters/junit.js' {
  declare module.exports: $Exports<'jscs/lib/reporters/junit'>;
}
declare module 'jscs/lib/reporters/summary.js' {
  declare module.exports: $Exports<'jscs/lib/reporters/summary'>;
}
declare module 'jscs/lib/reporters/text.js' {
  declare module.exports: $Exports<'jscs/lib/reporters/text'>;
}
declare module 'jscs/lib/reporters/unix.js' {
  declare module.exports: $Exports<'jscs/lib/reporters/unix'>;
}
declare module 'jscs/lib/rules/disallow-anonymous-functions.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-anonymous-functions'>;
}
declare module 'jscs/lib/rules/disallow-array-destructuring-return.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-array-destructuring-return'>;
}
declare module 'jscs/lib/rules/disallow-arrow-functions.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-arrow-functions'>;
}
declare module 'jscs/lib/rules/disallow-capitalized-comments.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-capitalized-comments'>;
}
declare module 'jscs/lib/rules/disallow-comma-before-line-break.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-comma-before-line-break'>;
}
declare module 'jscs/lib/rules/disallow-curly-braces.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-curly-braces'>;
}
declare module 'jscs/lib/rules/disallow-dangling-underscores.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-dangling-underscores'>;
}
declare module 'jscs/lib/rules/disallow-empty-blocks.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-empty-blocks'>;
}
declare module 'jscs/lib/rules/disallow-function-declarations.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-function-declarations'>;
}
declare module 'jscs/lib/rules/disallow-identical-destructuring-names.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-identical-destructuring-names'>;
}
declare module 'jscs/lib/rules/disallow-identifier-names.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-identifier-names'>;
}
declare module 'jscs/lib/rules/disallow-implicit-type-conversion.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-implicit-type-conversion'>;
}
declare module 'jscs/lib/rules/disallow-keywords-in-comments.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-keywords-in-comments'>;
}
declare module 'jscs/lib/rules/disallow-keywords-on-new-line.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-keywords-on-new-line'>;
}
declare module 'jscs/lib/rules/disallow-keywords.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-keywords'>;
}
declare module 'jscs/lib/rules/disallow-mixed-spaces-and-tabs.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-mixed-spaces-and-tabs'>;
}
declare module 'jscs/lib/rules/disallow-multi-line-ternary.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-multi-line-ternary'>;
}
declare module 'jscs/lib/rules/disallow-multiple-line-breaks.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-multiple-line-breaks'>;
}
declare module 'jscs/lib/rules/disallow-multiple-line-strings.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-multiple-line-strings'>;
}
declare module 'jscs/lib/rules/disallow-multiple-spaces.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-multiple-spaces'>;
}
declare module 'jscs/lib/rules/disallow-multiple-var-decl.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-multiple-var-decl'>;
}
declare module 'jscs/lib/rules/disallow-named-unassigned-functions.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-named-unassigned-functions'>;
}
declare module 'jscs/lib/rules/disallow-nested-ternaries.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-nested-ternaries'>;
}
declare module 'jscs/lib/rules/disallow-newline-before-block-statements.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-newline-before-block-statements'>;
}
declare module 'jscs/lib/rules/disallow-node-types.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-node-types'>;
}
declare module 'jscs/lib/rules/disallow-not-operators-in-conditionals.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-not-operators-in-conditionals'>;
}
declare module 'jscs/lib/rules/disallow-object-keys-on-new-line.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-object-keys-on-new-line'>;
}
declare module 'jscs/lib/rules/disallow-operator-before-line-break.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-operator-before-line-break'>;
}
declare module 'jscs/lib/rules/disallow-padding-newlines-after-blocks.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-padding-newlines-after-blocks'>;
}
declare module 'jscs/lib/rules/disallow-padding-newlines-after-use-strict.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-padding-newlines-after-use-strict'>;
}
declare module 'jscs/lib/rules/disallow-padding-newlines-before-export.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-padding-newlines-before-export'>;
}
declare module 'jscs/lib/rules/disallow-padding-newlines-before-keywords.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-padding-newlines-before-keywords'>;
}
declare module 'jscs/lib/rules/disallow-padding-newlines-before-line-comments.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-padding-newlines-before-line-comments'>;
}
declare module 'jscs/lib/rules/disallow-padding-newlines-in-blocks.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-padding-newlines-in-blocks'>;
}
declare module 'jscs/lib/rules/disallow-padding-newlines-in-objects.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-padding-newlines-in-objects'>;
}
declare module 'jscs/lib/rules/disallow-parentheses-around-arrow-param.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-parentheses-around-arrow-param'>;
}
declare module 'jscs/lib/rules/disallow-quoted-keys-in-objects.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-quoted-keys-in-objects'>;
}
declare module 'jscs/lib/rules/disallow-semicolons.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-semicolons'>;
}
declare module 'jscs/lib/rules/disallow-shorthand-arrow-functions.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-shorthand-arrow-functions'>;
}
declare module 'jscs/lib/rules/disallow-space-after-binary-operators.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-space-after-binary-operators'>;
}
declare module 'jscs/lib/rules/disallow-space-after-comma.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-space-after-comma'>;
}
declare module 'jscs/lib/rules/disallow-space-after-keywords.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-space-after-keywords'>;
}
declare module 'jscs/lib/rules/disallow-space-after-line-comment.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-space-after-line-comment'>;
}
declare module 'jscs/lib/rules/disallow-space-after-object-keys.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-space-after-object-keys'>;
}
declare module 'jscs/lib/rules/disallow-space-after-prefix-unary-operators.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-space-after-prefix-unary-operators'>;
}
declare module 'jscs/lib/rules/disallow-space-before-binary-operators.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-space-before-binary-operators'>;
}
declare module 'jscs/lib/rules/disallow-space-before-block-statements.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-space-before-block-statements'>;
}
declare module 'jscs/lib/rules/disallow-space-before-comma.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-space-before-comma'>;
}
declare module 'jscs/lib/rules/disallow-space-before-keywords.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-space-before-keywords'>;
}
declare module 'jscs/lib/rules/disallow-space-before-object-values.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-space-before-object-values'>;
}
declare module 'jscs/lib/rules/disallow-space-before-postfix-unary-operators.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-space-before-postfix-unary-operators'>;
}
declare module 'jscs/lib/rules/disallow-space-before-semicolon.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-space-before-semicolon'>;
}
declare module 'jscs/lib/rules/disallow-space-between-arguments.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-space-between-arguments'>;
}
declare module 'jscs/lib/rules/disallow-spaces-in-anonymous-function-expression.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-spaces-in-anonymous-function-expression'>;
}
declare module 'jscs/lib/rules/disallow-spaces-in-call-expression.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-spaces-in-call-expression'>;
}
declare module 'jscs/lib/rules/disallow-spaces-in-conditional-expression.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-spaces-in-conditional-expression'>;
}
declare module 'jscs/lib/rules/disallow-spaces-in-for-statement.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-spaces-in-for-statement'>;
}
declare module 'jscs/lib/rules/disallow-spaces-in-function-declaration.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-spaces-in-function-declaration'>;
}
declare module 'jscs/lib/rules/disallow-spaces-in-function-expression.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-spaces-in-function-expression'>;
}
declare module 'jscs/lib/rules/disallow-spaces-in-function.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-spaces-in-function'>;
}
declare module 'jscs/lib/rules/disallow-spaces-in-generator.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-spaces-in-generator'>;
}
declare module 'jscs/lib/rules/disallow-spaces-in-named-function-expression.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-spaces-in-named-function-expression'>;
}
declare module 'jscs/lib/rules/disallow-spaces-inside-array-brackets.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-spaces-inside-array-brackets'>;
}
declare module 'jscs/lib/rules/disallow-spaces-inside-brackets.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-spaces-inside-brackets'>;
}
declare module 'jscs/lib/rules/disallow-spaces-inside-imported-object-braces.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-spaces-inside-imported-object-braces'>;
}
declare module 'jscs/lib/rules/disallow-spaces-inside-object-brackets.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-spaces-inside-object-brackets'>;
}
declare module 'jscs/lib/rules/disallow-spaces-inside-parentheses.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-spaces-inside-parentheses'>;
}
declare module 'jscs/lib/rules/disallow-spaces-inside-parenthesized-expression.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-spaces-inside-parenthesized-expression'>;
}
declare module 'jscs/lib/rules/disallow-spaces-inside-template-string-placeholders.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-spaces-inside-template-string-placeholders'>;
}
declare module 'jscs/lib/rules/disallow-tabs.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-tabs'>;
}
declare module 'jscs/lib/rules/disallow-trailing-comma.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-trailing-comma'>;
}
declare module 'jscs/lib/rules/disallow-trailing-whitespace.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-trailing-whitespace'>;
}
declare module 'jscs/lib/rules/disallow-unused-params.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-unused-params'>;
}
declare module 'jscs/lib/rules/disallow-unused-variables.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-unused-variables'>;
}
declare module 'jscs/lib/rules/disallow-var.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-var'>;
}
declare module 'jscs/lib/rules/disallow-yoda-conditions.js' {
  declare module.exports: $Exports<'jscs/lib/rules/disallow-yoda-conditions'>;
}
declare module 'jscs/lib/rules/jsdoc.js' {
  declare module.exports: $Exports<'jscs/lib/rules/jsdoc'>;
}
declare module 'jscs/lib/rules/maximum-line-length.js' {
  declare module.exports: $Exports<'jscs/lib/rules/maximum-line-length'>;
}
declare module 'jscs/lib/rules/maximum-number-of-lines.js' {
  declare module.exports: $Exports<'jscs/lib/rules/maximum-number-of-lines'>;
}
declare module 'jscs/lib/rules/require-aligned-multiline-params.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-aligned-multiline-params'>;
}
declare module 'jscs/lib/rules/require-aligned-object-values.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-aligned-object-values'>;
}
declare module 'jscs/lib/rules/require-anonymous-functions.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-anonymous-functions'>;
}
declare module 'jscs/lib/rules/require-array-destructuring.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-array-destructuring'>;
}
declare module 'jscs/lib/rules/require-arrow-functions.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-arrow-functions'>;
}
declare module 'jscs/lib/rules/require-blocks-on-newline.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-blocks-on-newline'>;
}
declare module 'jscs/lib/rules/require-camelcase-or-uppercase-identifiers.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-camelcase-or-uppercase-identifiers'>;
}
declare module 'jscs/lib/rules/require-capitalized-comments.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-capitalized-comments'>;
}
declare module 'jscs/lib/rules/require-capitalized-constructors-new.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-capitalized-constructors-new'>;
}
declare module 'jscs/lib/rules/require-capitalized-constructors.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-capitalized-constructors'>;
}
declare module 'jscs/lib/rules/require-comma-before-line-break.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-comma-before-line-break'>;
}
declare module 'jscs/lib/rules/require-curly-braces.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-curly-braces'>;
}
declare module 'jscs/lib/rules/require-dollar-before-jquery-assignment.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-dollar-before-jquery-assignment'>;
}
declare module 'jscs/lib/rules/require-dot-notation.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-dot-notation'>;
}
declare module 'jscs/lib/rules/require-early-return.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-early-return'>;
}
declare module 'jscs/lib/rules/require-enhanced-object-literals.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-enhanced-object-literals'>;
}
declare module 'jscs/lib/rules/require-function-declarations.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-function-declarations'>;
}
declare module 'jscs/lib/rules/require-imports-alphabetized.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-imports-alphabetized'>;
}
declare module 'jscs/lib/rules/require-keywords-on-new-line.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-keywords-on-new-line'>;
}
declare module 'jscs/lib/rules/require-line-break-after-variable-assignment.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-line-break-after-variable-assignment'>;
}
declare module 'jscs/lib/rules/require-line-feed-at-file-end.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-line-feed-at-file-end'>;
}
declare module 'jscs/lib/rules/require-matching-function-name.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-matching-function-name'>;
}
declare module 'jscs/lib/rules/require-multi-line-ternary.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-multi-line-ternary'>;
}
declare module 'jscs/lib/rules/require-multiple-var-decl.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-multiple-var-decl'>;
}
declare module 'jscs/lib/rules/require-named-unassigned-functions.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-named-unassigned-functions'>;
}
declare module 'jscs/lib/rules/require-newline-before-block-statements.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-newline-before-block-statements'>;
}
declare module 'jscs/lib/rules/require-newline-before-single-statements-in-if.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-newline-before-single-statements-in-if'>;
}
declare module 'jscs/lib/rules/require-numeric-literals.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-numeric-literals'>;
}
declare module 'jscs/lib/rules/require-object-destructuring.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-object-destructuring'>;
}
declare module 'jscs/lib/rules/require-object-keys-on-new-line.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-object-keys-on-new-line'>;
}
declare module 'jscs/lib/rules/require-operator-before-line-break.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-operator-before-line-break'>;
}
declare module 'jscs/lib/rules/require-padding-newline-after-variable-declaration.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-padding-newline-after-variable-declaration'>;
}
declare module 'jscs/lib/rules/require-padding-newlines-after-blocks.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-padding-newlines-after-blocks'>;
}
declare module 'jscs/lib/rules/require-padding-newlines-after-use-strict.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-padding-newlines-after-use-strict'>;
}
declare module 'jscs/lib/rules/require-padding-newlines-before-export.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-padding-newlines-before-export'>;
}
declare module 'jscs/lib/rules/require-padding-newlines-before-keywords.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-padding-newlines-before-keywords'>;
}
declare module 'jscs/lib/rules/require-padding-newlines-before-line-comments.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-padding-newlines-before-line-comments'>;
}
declare module 'jscs/lib/rules/require-padding-newlines-in-blocks.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-padding-newlines-in-blocks'>;
}
declare module 'jscs/lib/rules/require-padding-newlines-in-objects.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-padding-newlines-in-objects'>;
}
declare module 'jscs/lib/rules/require-parentheses-around-arrow-param.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-parentheses-around-arrow-param'>;
}
declare module 'jscs/lib/rules/require-parentheses-around-iife.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-parentheses-around-iife'>;
}
declare module 'jscs/lib/rules/require-quoted-keys-in-objects.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-quoted-keys-in-objects'>;
}
declare module 'jscs/lib/rules/require-semicolons.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-semicolons'>;
}
declare module 'jscs/lib/rules/require-shorthand-arrow-functions.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-shorthand-arrow-functions'>;
}
declare module 'jscs/lib/rules/require-space-after-binary-operators.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-space-after-binary-operators'>;
}
declare module 'jscs/lib/rules/require-space-after-comma.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-space-after-comma'>;
}
declare module 'jscs/lib/rules/require-space-after-keywords.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-space-after-keywords'>;
}
declare module 'jscs/lib/rules/require-space-after-line-comment.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-space-after-line-comment'>;
}
declare module 'jscs/lib/rules/require-space-after-object-keys.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-space-after-object-keys'>;
}
declare module 'jscs/lib/rules/require-space-after-prefix-unary-operators.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-space-after-prefix-unary-operators'>;
}
declare module 'jscs/lib/rules/require-space-before-binary-operators.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-space-before-binary-operators'>;
}
declare module 'jscs/lib/rules/require-space-before-block-statements.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-space-before-block-statements'>;
}
declare module 'jscs/lib/rules/require-space-before-comma.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-space-before-comma'>;
}
declare module 'jscs/lib/rules/require-space-before-destructured-values.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-space-before-destructured-values'>;
}
declare module 'jscs/lib/rules/require-space-before-keywords.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-space-before-keywords'>;
}
declare module 'jscs/lib/rules/require-space-before-object-values.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-space-before-object-values'>;
}
declare module 'jscs/lib/rules/require-space-before-postfix-unary-operators.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-space-before-postfix-unary-operators'>;
}
declare module 'jscs/lib/rules/require-space-between-arguments.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-space-between-arguments'>;
}
declare module 'jscs/lib/rules/require-spaces-in-anonymous-function-expression.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-spaces-in-anonymous-function-expression'>;
}
declare module 'jscs/lib/rules/require-spaces-in-call-expression.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-spaces-in-call-expression'>;
}
declare module 'jscs/lib/rules/require-spaces-in-conditional-expression.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-spaces-in-conditional-expression'>;
}
declare module 'jscs/lib/rules/require-spaces-in-for-statement.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-spaces-in-for-statement'>;
}
declare module 'jscs/lib/rules/require-spaces-in-function-declaration.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-spaces-in-function-declaration'>;
}
declare module 'jscs/lib/rules/require-spaces-in-function-expression.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-spaces-in-function-expression'>;
}
declare module 'jscs/lib/rules/require-spaces-in-function.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-spaces-in-function'>;
}
declare module 'jscs/lib/rules/require-spaces-in-generator.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-spaces-in-generator'>;
}
declare module 'jscs/lib/rules/require-spaces-in-named-function-expression.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-spaces-in-named-function-expression'>;
}
declare module 'jscs/lib/rules/require-spaces-inside-array-brackets.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-spaces-inside-array-brackets'>;
}
declare module 'jscs/lib/rules/require-spaces-inside-brackets.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-spaces-inside-brackets'>;
}
declare module 'jscs/lib/rules/require-spaces-inside-imported-object-braces.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-spaces-inside-imported-object-braces'>;
}
declare module 'jscs/lib/rules/require-spaces-inside-object-brackets.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-spaces-inside-object-brackets'>;
}
declare module 'jscs/lib/rules/require-spaces-inside-parentheses.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-spaces-inside-parentheses'>;
}
declare module 'jscs/lib/rules/require-spaces-inside-parenthesized-expression.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-spaces-inside-parenthesized-expression'>;
}
declare module 'jscs/lib/rules/require-spread.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-spread'>;
}
declare module 'jscs/lib/rules/require-template-strings.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-template-strings'>;
}
declare module 'jscs/lib/rules/require-trailing-comma.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-trailing-comma'>;
}
declare module 'jscs/lib/rules/require-use-strict.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-use-strict'>;
}
declare module 'jscs/lib/rules/require-var-decl-first.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-var-decl-first'>;
}
declare module 'jscs/lib/rules/require-yoda-conditions.js' {
  declare module.exports: $Exports<'jscs/lib/rules/require-yoda-conditions'>;
}
declare module 'jscs/lib/rules/safe-context-keyword.js' {
  declare module.exports: $Exports<'jscs/lib/rules/safe-context-keyword'>;
}
declare module 'jscs/lib/rules/validate-aligned-function-parameters.js' {
  declare module.exports: $Exports<'jscs/lib/rules/validate-aligned-function-parameters'>;
}
declare module 'jscs/lib/rules/validate-comment-position.js' {
  declare module.exports: $Exports<'jscs/lib/rules/validate-comment-position'>;
}
declare module 'jscs/lib/rules/validate-indentation.js' {
  declare module.exports: $Exports<'jscs/lib/rules/validate-indentation'>;
}
declare module 'jscs/lib/rules/validate-line-breaks.js' {
  declare module.exports: $Exports<'jscs/lib/rules/validate-line-breaks'>;
}
declare module 'jscs/lib/rules/validate-newline-after-array-elements.js' {
  declare module.exports: $Exports<'jscs/lib/rules/validate-newline-after-array-elements'>;
}
declare module 'jscs/lib/rules/validate-order-in-object-keys.js' {
  declare module.exports: $Exports<'jscs/lib/rules/validate-order-in-object-keys'>;
}
declare module 'jscs/lib/rules/validate-parameter-separator.js' {
  declare module.exports: $Exports<'jscs/lib/rules/validate-parameter-separator'>;
}
declare module 'jscs/lib/rules/validate-quote-marks.js' {
  declare module.exports: $Exports<'jscs/lib/rules/validate-quote-marks'>;
}
declare module 'jscs/lib/string-checker.js' {
  declare module.exports: $Exports<'jscs/lib/string-checker'>;
}
declare module 'jscs/lib/token-assert.js' {
  declare module.exports: $Exports<'jscs/lib/token-assert'>;
}
declare module 'jscs/lib/token-categorizer.js' {
  declare module.exports: $Exports<'jscs/lib/token-categorizer'>;
}
declare module 'jscs/lib/token-index.js' {
  declare module.exports: $Exports<'jscs/lib/token-index'>;
}
declare module 'jscs/lib/tree-iterator.js' {
  declare module.exports: $Exports<'jscs/lib/tree-iterator'>;
}
declare module 'jscs/lib/utils.js' {
  declare module.exports: $Exports<'jscs/lib/utils'>;
}
declare module 'jscs/patterns/identifiers-ES5.js' {
  declare module.exports: $Exports<'jscs/patterns/identifiers-ES5'>;
}
declare module 'jscs/patterns/identifiers-ES6.js' {
  declare module.exports: $Exports<'jscs/patterns/identifiers-ES6'>;
}
declare module 'jscs/patterns/L.js' {
  declare module.exports: $Exports<'jscs/patterns/L'>;
}
declare module 'jscs/patterns/Ll.js' {
  declare module.exports: $Exports<'jscs/patterns/Ll'>;
}
declare module 'jscs/patterns/Lu.js' {
  declare module.exports: $Exports<'jscs/patterns/Lu'>;
}
