// flow-typed signature: 527a284887dbda184143f5429ec51dee
// flow-typed version: <<STUB>>/lodash.keyby_v^4.6.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.keyby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.keyby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.keyby/index' {
  declare module.exports: $Exports<'lodash.keyby'>;
}
declare module 'lodash.keyby/index.js' {
  declare module.exports: $Exports<'lodash.keyby'>;
}
