// flow-typed signature: eba8d33959b223c8cdb77fa80b029f0d
// flow-typed version: <<STUB>>/prop-types-extra_v^1.0.1/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prop-types-extra'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prop-types-extra' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prop-types-extra/lib/all' {
  declare module.exports: any;
}

declare module 'prop-types-extra/lib/componentOrElement' {
  declare module.exports: any;
}

declare module 'prop-types-extra/lib/deprecated' {
  declare module.exports: any;
}

declare module 'prop-types-extra/lib/elementType' {
  declare module.exports: any;
}

declare module 'prop-types-extra/lib/index' {
  declare module.exports: any;
}

declare module 'prop-types-extra/lib/isRequiredForA11y' {
  declare module.exports: any;
}

declare module 'prop-types-extra/lib/utils/createChainableTypeChecker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prop-types-extra/lib/all.js' {
  declare module.exports: $Exports<'prop-types-extra/lib/all'>;
}
declare module 'prop-types-extra/lib/componentOrElement.js' {
  declare module.exports: $Exports<'prop-types-extra/lib/componentOrElement'>;
}
declare module 'prop-types-extra/lib/deprecated.js' {
  declare module.exports: $Exports<'prop-types-extra/lib/deprecated'>;
}
declare module 'prop-types-extra/lib/elementType.js' {
  declare module.exports: $Exports<'prop-types-extra/lib/elementType'>;
}
declare module 'prop-types-extra/lib/index.js' {
  declare module.exports: $Exports<'prop-types-extra/lib/index'>;
}
declare module 'prop-types-extra/lib/isRequiredForA11y.js' {
  declare module.exports: $Exports<'prop-types-extra/lib/isRequiredForA11y'>;
}
declare module 'prop-types-extra/lib/utils/createChainableTypeChecker.js' {
  declare module.exports: $Exports<'prop-types-extra/lib/utils/createChainableTypeChecker'>;
}
