// flow-typed signature: 7c32cd31cbdca68557e9e7b94914a54f
// flow-typed version: <<STUB>>/properties-loader_v0.0.1/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'properties-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'properties-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'properties-loader/index' {
  declare module.exports: $Exports<'properties-loader'>;
}
declare module 'properties-loader/index.js' {
  declare module.exports: $Exports<'properties-loader'>;
}
