// flow-typed signature: c994aaf6407ff3f7b4487bb5dd071156
// flow-typed version: <<STUB>>/react-string-replace_v^0.4.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-string-replace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-string-replace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-string-replace/index' {
  declare module.exports: $Exports<'react-string-replace'>;
}
declare module 'react-string-replace/index.js' {
  declare module.exports: $Exports<'react-string-replace'>;
}
