// flow-typed signature: d4ca019ba319a8be54aa391248466142
// flow-typed version: <<STUB>>/react-popover_v^0.5.4/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-popover'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-popover' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-popover/build/index' {
  declare module.exports: any;
}

declare module 'react-popover/build/layout' {
  declare module.exports: any;
}

declare module 'react-popover/build/on-resize' {
  declare module.exports: any;
}

declare module 'react-popover/build/platform' {
  declare module.exports: any;
}

declare module 'react-popover/build/tip' {
  declare module.exports: any;
}

declare module 'react-popover/build/utils' {
  declare module.exports: any;
}

declare module 'react-popover/lib/index' {
  declare module.exports: any;
}

declare module 'react-popover/lib/layout' {
  declare module.exports: any;
}

declare module 'react-popover/lib/on-resize' {
  declare module.exports: any;
}

declare module 'react-popover/lib/platform' {
  declare module.exports: any;
}

declare module 'react-popover/lib/tip' {
  declare module.exports: any;
}

declare module 'react-popover/lib/utils' {
  declare module.exports: any;
}

declare module 'react-popover/stories/index' {
  declare module.exports: any;
}

declare module 'react-popover/stories/playground/main' {
  declare module.exports: any;
}

declare module 'react-popover/stories/rows/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-popover/build/index.js' {
  declare module.exports: $Exports<'react-popover/build/index'>;
}
declare module 'react-popover/build/layout.js' {
  declare module.exports: $Exports<'react-popover/build/layout'>;
}
declare module 'react-popover/build/on-resize.js' {
  declare module.exports: $Exports<'react-popover/build/on-resize'>;
}
declare module 'react-popover/build/platform.js' {
  declare module.exports: $Exports<'react-popover/build/platform'>;
}
declare module 'react-popover/build/tip.js' {
  declare module.exports: $Exports<'react-popover/build/tip'>;
}
declare module 'react-popover/build/utils.js' {
  declare module.exports: $Exports<'react-popover/build/utils'>;
}
declare module 'react-popover/index' {
  declare module.exports: $Exports<'react-popover'>;
}
declare module 'react-popover/index.js' {
  declare module.exports: $Exports<'react-popover'>;
}
declare module 'react-popover/lib/index.js' {
  declare module.exports: $Exports<'react-popover/lib/index'>;
}
declare module 'react-popover/lib/layout.js' {
  declare module.exports: $Exports<'react-popover/lib/layout'>;
}
declare module 'react-popover/lib/on-resize.js' {
  declare module.exports: $Exports<'react-popover/lib/on-resize'>;
}
declare module 'react-popover/lib/platform.js' {
  declare module.exports: $Exports<'react-popover/lib/platform'>;
}
declare module 'react-popover/lib/tip.js' {
  declare module.exports: $Exports<'react-popover/lib/tip'>;
}
declare module 'react-popover/lib/utils.js' {
  declare module.exports: $Exports<'react-popover/lib/utils'>;
}
declare module 'react-popover/stories/index.js' {
  declare module.exports: $Exports<'react-popover/stories/index'>;
}
declare module 'react-popover/stories/playground/main.js' {
  declare module.exports: $Exports<'react-popover/stories/playground/main'>;
}
declare module 'react-popover/stories/rows/main.js' {
  declare module.exports: $Exports<'react-popover/stories/rows/main'>;
}
