// flow-typed signature: 17ffb915e4c1ed5b46216e396169d177
// flow-typed version: <<STUB>>/uglify-save-license_v^0.4.1/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uglify-save-license'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uglify-save-license' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uglify-save-license/uglify-save-license' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uglify-save-license/uglify-save-license.js' {
  declare module.exports: $Exports<'uglify-save-license/uglify-save-license'>;
}
