// flow-typed signature: 5b8ddfa30c68358df68afc63a0d42305
// flow-typed version: <<STUB>>/@atlaskit/css-reset_v^2.0.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/css-reset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/css-reset' {
  declare module.exports: any;
}
