// flow-typed signature: a4d2041b1c1369b143cb13596d463e9a
// flow-typed version: <<STUB>>/@atlaskit/css-reset_v^3.0.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/css-reset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/css-reset' {
  declare module.exports: any;
}
