// flow-typed signature: 8b78e39e58cc08fbd9c32389a82e9421
// flow-typed version: <<STUB>>/@atlaskit/util-shared-styles_v^3.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/util-shared-styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/util-shared-styles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/util-shared-styles/build/jsVars' {
  declare module.exports: any;
}

declare module '@atlaskit/util-shared-styles/dist/bundle-cjs' {
  declare module.exports: any;
}

declare module '@atlaskit/util-shared-styles/dist/bundle-cjs.min' {
  declare module.exports: any;
}

declare module '@atlaskit/util-shared-styles/dist/bundle' {
  declare module.exports: any;
}

declare module '@atlaskit/util-shared-styles/dist/bundle.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/util-shared-styles/build/jsVars.js' {
  declare module.exports: $Exports<'@atlaskit/util-shared-styles/build/jsVars'>;
}
declare module '@atlaskit/util-shared-styles/dist/bundle-cjs.js' {
  declare module.exports: $Exports<'@atlaskit/util-shared-styles/dist/bundle-cjs'>;
}
declare module '@atlaskit/util-shared-styles/dist/bundle-cjs.min.js' {
  declare module.exports: $Exports<'@atlaskit/util-shared-styles/dist/bundle-cjs.min'>;
}
declare module '@atlaskit/util-shared-styles/dist/bundle.js' {
  declare module.exports: $Exports<'@atlaskit/util-shared-styles/dist/bundle'>;
}
declare module '@atlaskit/util-shared-styles/dist/bundle.min.js' {
  declare module.exports: $Exports<'@atlaskit/util-shared-styles/dist/bundle.min'>;
}
