import com.atlassian.jira.component.ComponentAccessor
import com.atlassian.jira.security.JiraAuthenticationContext
import com.atlassian.jira.web.SessionKeys;

ComponentAccessor.jiraAuthenticationContext.getUser()
ComponentAccessor.jiraAuthenticationContext.user
ComponentAccessor.userUtil.activeUserCount
ComponentAccessor.getOsgiComponentReference(JiraAuthenticationContext)

return SessionKeys.TEMP_ATTACHMENTS
